# -*- coding: utf-8 -*-
"""Python Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FKBtJmUG-TTmwTatBwLYVXlArrqLWkv4
"""

print('hello world')
print('This is my first Python program uploaded to GitHub.')

